---
abstract: 'Run Kwalitee tests including optional indicators, especially, prereq_matches_use'
author:
  - 'Yasutaka ATARASHI <yakex@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Kwalitee-Extra
no_index:
  directory:
    - t/08-_get_packages_not_indexed
requires:
  MetaCPAN::API::Tiny: 0
  Module::CPANTS::Analyse: 0.87
  Module::CoreList: 2.31_01
  Module::Extract::Namespaces: 0
  Test::Builder::Tester: 0
  perl: 5.006
  version: 0.77
version: v0.0.8
